### ISSUE TITLE
Database grows too fast

### ISSUE THREAD

**Issue by Jazzer9F** [Jazzer9F/RadBot#3]
Bot uses HDF5 data store, which somehow doesn't like deleting/re-entering. The file size grows much faster than the number of actions in the DataFrame. Could have something to do with the warning that it needs to pickle many columns when it writes to disk.

**Comment by Mleekko** [comment]
HDF5 does not cleanup deleted data from the file automatically (see [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#delete-from-a-table)).
  You need to compact it manually
  ```bash
  ptrepack --chunkshape=auto --propindexes --complevel=0 --complib=blosc stake.h5 stake_new.h5
  ```
  and then
  ```bash
  mv -f stake_new.h5 stake.h5
  ```
-----
See https://github.com/Jazzer9F/RadBot/pull/5/commits/412563cb43c967e6dfe9aad8b869d0016e4c7722#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17

**Comment by Jazzer9F** [comment]
Thanks! So I can just repack it every month or so and it should be fine.
Or could look for another database that would deal with this more gracefully.
